[package]
name = "tiny_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = "2.0.72"
quote = "1.0.36"
# proc-macro2 = "1.0.86"
iced = { version = "0.12.1", features = ["image", "advanced", "tokio"] }

[lib]
proc-macro = true
